project_id = "ojxydihfvorglvmqyyaq"

[functions.list-admin-users]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.update-admin-password]
verify_jwt = false

[functions.upload-to-drive]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.reset-user-mfa]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

